language: php
php:
  - 5.5
  - 5.4
  - hhvm

before_script:
  - mysql -e 'create database dabl_test;'
  - psql -c 'create database dabl_test;' -U postgres
script:
  - phpunit -c tests/phpunit.xml tests/
